spring.application.name=exercise-data-jpa-product

#Datasource properties
spring.datasource.url=jdbc:postgresql://ballast.proxy.rlwy.net:59012/railway
spring.datasource.username=postgres
spring.datasource.password=fyETGAiPUMQphYFUOxmSBLbkpXBYWjnn
spring.datasource.driver-class-name=org.postgresql.Driver


#Data JPA and Hibernate properties
spring.main.banner-mode= off

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
